import numpy.typing as npt
def crop_positions(x0: int, y0: int, x_delta: int, y_delta: int, face_percent: int, width: int, height: int, top: int, bottom: int, left: int, right: int) -> tuple[int, int, int, int]: ...
def calc_alpha_beta(hist: npt.NDArray) -> tuple[float, float]: ...
