from typing import Optional
from numpy.typing import NDArray
import numpy as np

def crop_positions(face: tuple[float, float, float, float], face_percent: int, dimensions: tuple[int, int], padding: tuple[int, int, int, int]) -> Optional[tuple[int, int, int, int]]: ...
def gamma(gamma_value: float) -> NDArray: ...
def calculate_dimensions(height: int, width: int, target_height: int) -> tuple[int, float]: ...
def get_rotation_matrix(left_eye_landmarks: NDArray, right_eye_landmarks: NDArray, scale_factor: float) -> NDArray: ...
def reshape_buffer_to_image(buffer: bytes, height: int, width: int) -> NDArray: ...
def correct_exposure(image: NDArray, exposure: bool, video: bool) -> NDArray: ...
def validate_files(files: list[str], categories: list[int]) -> NDArray[np.bool_]: ...
def verify_file_type(file_path: str, category: int) -> bool: ...
