from numpy.typing import NDArray
def crop_positions(x0: int, y0: int, x_delta: int, y_delta: int, face_percent: int, width: int, height: int, top: int, bottom: int, left: int, right: int) -> tuple[int, int, int, int]: ...
def calc_alpha_beta(hist: NDArray) -> tuple[float, float]: ...
def gamma(gamma_value: float) -> NDArray: ...
def calculate_dimensions(height: int, width: int, target_height: int) -> tuple[int, float]: ...
def get_rotation_matrix(left_eye_landmarks_x: NDArray, left_eye_landmarks_y: NDArray, right_eye_landmarks_x: NDArray, right_eye_landmarks_y: NDArray, scale_factor: float) -> tuple[NDArray, float]: ...