class PathSecurityError(Exception):
    message: str
    def __init__(self, message: str) -> None: ...
    def __str__(self) -> str: ...

def sanitize_path(
    path_str: str,
    allowed_operations: tuple[str, ...] = ('read', 'write'),
    max_path_length: int = 4096,
    follow_symlinks: bool = False
) -> str: ...

def get_safe_error_message(error_msg: str) -> str: ...
