from enum import Enum
from typing import Tuple


class GuiIcon(Enum):
    CLAPPERBOARD = 'resources\\icons\\clapperboard.svg'
    CANCEL = 'resources\\icons\\cancel.svg'
    CROP = 'resources\\icons\\crop.svg'
    EXCEL = 'resources\\icons\\excel.svg'
    FOLDER = 'resources\\icons\\folder.svg'
    LOGO = 'resources\\logos\\logo.svg'
    MULTIMEDIA_MUTE = 'resources\\icons\\multimedia_mute.svg'
    MULTIMEDIA_PAUSE = 'resources\\icons\\multimedia_pause.svg'
    MULTIMEDIA_PLAY = 'resources\\icons\\multimedia_play.svg'
    MULTIMEDIA_UNMUTE = 'resources\\icons\\multimedia_unmute.svg'
    MULTIMEDIA_STOP = 'resources\\icons\\multimedia_stop.svg'
    MULTIMEDIA_LEFT = 'resources\\icons\\multimedia_left.svg'
    MULTIMEDIA_RIGHT = 'resources\\icons\\multimedia_right.svg'
    MULTIMEDIA_REWIND = 'resources\\icons\\multimedia_rewind.svg'
    MULTIMEDIA_FASTFWD = 'resources\\icons\\multimedia_fastfwd.svg'
    MULTIMEDIA_BEGINING = 'resources\\icons\\multimedia_begining.svg'
    MULTIMEDIA_END = 'resources\\icons\\multimedia_end.svg'
    MULTIMEDIA_LEFTMARKER = 'resources\\icons\\multimedia_leftmarker.svg'
    MULTIMEDIA_RIGHTMARKER = 'resources\\icons\\multimedia_rightmarker.svg'
    MULTIMEDIA_CROPVIDEO = 'resources\\icons\\crop_video.svg'
    MULTIMEDIA_LABEL_A = 'resources\\icons\\marker_label_a.svg'
    MULTIMEDIA_LABEL_B = 'resources\\icons\\marker_label_b.svg'
    PICTURE = 'resources\\icons\\picture.svg'
    # RADIO_NONE: Tuple = 'resources/icons/file_no_checked.svg', 'resources/icons/file_no_unchecked.svg'
    # RADIO_BMP: Tuple = 'resources/icons/file_bmp_checked.svg', 'resources/icons/file_bmp_unchecked.svg'
    # RADIO_JPG: Tuple = 'resources/icons/file_jpg_checked.svg', 'resources/icons/file_jpg_unchecked.svg'
    # RADIO_PNG: Tuple = 'resources/icons/file_png_checked.svg', 'resources/icons/file_png_unchecked.svg'
    # RADIO_TIFF: Tuple = 'resources/icons/file_tiff_checked.svg', 'resources/icons/file_tiff_unchecked.svg'
    # RADIO_WEBP: Tuple = 'resources/icons/file_webp_checked.svg', 'resources/icons/file_webp_unchecked.svg'
