from PyQt6.QtCore import QCoreApplication, QMetaObject, QSize, Qt
from PyQt6.QtGui import QIcon, QPixmap
from PyQt6.QtWidgets import QDialog, QFrame, QHBoxLayout, QLabel, QSizePolicy, QVBoxLayout


class UiDialog(QDialog):
    def __init__(self):
        super(UiDialog, self).__init__()
        self.setObjectName('Dialog')
        self.resize(347, 442)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QSize(347, 442))
        self.setMaximumSize(QSize(347, 442))
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setObjectName('verticalLayout')
        self.label = QLabel(parent=self)
        self.label.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QSize(329, 411))
        self.label.setText('')
        self.label.setPixmap(QPixmap('resources\\logos\\logo.svg'))
        self.setWindowIcon(QIcon('resources\\logos\\logo.ico'))
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName('label')
        self.verticalLayout.addWidget(self.label)
        self.frame = QFrame(parent=self)
        self.frame.setFrameShape(QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName('frame')
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.label_7 = QLabel(parent=self.frame)
        self.label_7.setMinimumSize(QSize(50, 0))
        self.label_7.setMaximumSize(QSize(50, 16_777_215))
        self.label_7.setTextFormat(Qt.TextFormat.AutoText)
        self.label_7.setAlignment(
            Qt.AlignmentFlag.AlignLeading | Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignTop)
        self.label_7.setObjectName('label_7')
        self.horizontalLayout.addWidget(self.label_7)
        self.label_8 = QLabel(parent=self.frame)
        self.label_8.setAlignment(
            Qt.AlignmentFlag.AlignLeading | Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignTop)
        self.label_8.setObjectName('label_8')
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QFrame(parent=self)
        self.frame_2.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName('frame_2')
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.label_4 = QLabel(parent=self.frame_2)
        self.label_4.setMinimumSize(QSize(50, 0))
        self.label_4.setMaximumSize(QSize(50, 16_777_215))
        self.label_4.setAlignment(
            Qt.AlignmentFlag.AlignLeading | Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignTop)
        self.label_4.setObjectName('label_4')
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QLabel(parent=self.frame_2)
        self.label_3.setAlignment(
            Qt.AlignmentFlag.AlignLeading | Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignTop)
        self.label_3.setObjectName('label_3')
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QFrame(parent=self)
        self.frame_3.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName('frame_3')
        self.horizontalLayout_3 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.frame_5 = QFrame(parent=self.frame_3)
        self.frame_5.setMinimumSize(QSize(50, 0))
        self.frame_5.setMaximumSize(QSize(50, 16_777_215))
        self.frame_5.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName('frame_5')
        self.verticalLayout_3 = QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.label_5 = QLabel(parent=self.frame_5)
        self.label_5.setMinimumSize(QSize(50, 0))
        self.label_5.setMaximumSize(QSize(50, 16_777_215))
        self.label_5.setLineWidth(0)
        self.label_5.setObjectName('label_5')
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_9 = QLabel(parent=self.frame_5)
        self.label_9.setMinimumSize(QSize(50, 0))
        self.label_9.setMaximumSize(QSize(50, 16_777_215))
        self.label_9.setLineWidth(0)
        self.label_9.setText('')
        self.label_9.setObjectName('label_9')
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_4 = QFrame(parent=self.frame_3)
        self.frame_4.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName('frame_4')
        self.verticalLayout_2 = QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(14, -1, 0, -1)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.label_6 = QLabel(parent=self.frame_4)
        self.label_6.setStyleSheet('')
        self.label_6.setLineWidth(0)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setObjectName('label_6')
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_2 = QLabel(parent=self.frame_4)
        self.label_2.setLineWidth(0)
        self.label_2.setAlignment(
            Qt.AlignmentFlag.AlignLeading | Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName('label_2')
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi()
        QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate('Dialog', 'About Face Cropper'))
        self.label_7.setText(_translate('Dialog', 'Version:'))
        self.label_8.setText(_translate('Dialog', '2.0.0'))
        self.label_4.setText(_translate('Dialog', 'Creator:'))
        self.label_3.setText(_translate('Dialog', 'Gregory Carnegie'))
        self.label_5.setText(_translate('Dialog', 'Credits:'))
        self.label_6.setText(
            _translate(
                'Dialog',
                "<a href=\"https://leblancfg.com/autocrop/\">François (leblancfg) Leblanc\'s autocrop library</a>"))
        self.label_2.setText(
            _translate(
                "Dialog",
                "<a href=\"https://bleedai.com/5-easy-effective-face-detection-algorithms-in-python/\">Bleed AI\'s \'Effective Face Detection\' article</a>"))
