from PyQt6.QtCore import QCoreApplication, QMetaObject, QSize
from PyQt6.QtGui import QIcon, QPixmap
from PyQt6.QtWidgets import QDialog, QHBoxLayout, QLabel, QSizePolicy, QVBoxLayout

from .image_widget import ImageWidget
from . import window_functions as wf


class UiDialog(QDialog):
    def __init__(self):
        super(UiDialog, self).__init__()
        self.setObjectName('Dialog')
        self.resize(347, 442)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QSize(347, 442))
        self.setMaximumSize(QSize(347, 442))
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setObjectName('verticalLayout')
        self.widget = ImageWidget(parent=self)
        self.widget.setObjectName('widget')
        self.widget.setImage(QPixmap('resources\\logos\\logo.svg'))
        self.setWindowIcon(QIcon('resources\\logos\\logo.ico'))
        self.verticalLayout.addWidget(self.widget)
        self.frame = wf.setup_frame('frame', parent=self)
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.label = QLabel(parent=self.frame)
        self.label.setObjectName('label')
        self.horizontalLayout_2.addWidget(self.label)
        self.label_5 = QLabel(parent=self.frame)
        self.label_5.setObjectName('label_5')
        self.horizontalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = wf.setup_frame('frame_2', parent=self)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.label_2 = QLabel(parent=self.frame_2)
        self.label_2.setObjectName('label_2')
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_6 = QLabel(parent=self.frame_2)
        self.label_6.setObjectName('label_6')
        self.horizontalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = wf.setup_frame('frame_3', parent=self)
        self.horizontalLayout = QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.frame_4 = wf.setup_frame('frame_4', parent=self)
        self.verticalLayout_2 = QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.label_3 = QLabel(parent=self.frame_4)
        self.label_3.setObjectName('label_3')
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QLabel(parent=self.frame_4)
        self.label_4.setText('')
        self.label_4.setObjectName('label_4')
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = wf.setup_frame('frame_5', parent=self)
        self.verticalLayout_3 = QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.label_7 = QLabel(parent=self.frame_5)
        self.label_7.setObjectName('label_7')
        self.label_7.setOpenExternalLinks(True)
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QLabel(parent=self.frame_5)
        self.label_8.setObjectName('label_8')
        self.label_8.setOpenExternalLinks(True)
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout.addWidget(self.frame_5)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)
        self.retranslateUi()
        QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate('Dialog', 'About Face Cropper'))
        self.label.setText(_translate('Dialog', 'Version:'))
        self.label_5.setText(_translate('Dialog', '2.0.0b1'))
        self.label_2.setText(_translate('Dialog', 'Creator:'))
        self.label_6.setText(_translate("Dialog", """<a href="https://github.com/gregorycarnegie/autocrop">Gregory 
        Carnegie</a>"""))
        self.label_3.setText(_translate('Dialog', 'Inspiration:'))
        self.label_7.setText(_translate('Dialog', """<a href="https://leblancfg.com/autocrop/">François Leblanc's 
        autocrop library</a>"""))
        self.label_8.setText(_translate('Dialog', """<a href="https://bleedaiacademy.com/5-easy-effective-face
        -detection-algorithms-in-python/">Bleed AI's Face Detection article</a>"""))
